### ISSUE TITLE
simpleITKWienerDeconvolution throws java.lang.NoSuchMethodError. Multiple simpleITK jars? 

### ISSUE THREAD

**Issue by chalkie666** [clij/clijx-assistant-simpleitk#4]
Hi Robert

I turned on the clij assistant extensions and IJ-ITK update sites (and bonej and the others to stop it complaining)
Testing simpleITKWienerDeconvolution from the menu item GUI, so i can catch the command in the macro recorder, 
it throws errors about missing methods and warnings about multiple jars. 

Should there be both
simpleitk-0.9.0.jar
and
simpleitk-2.1.0.dev54.jar
in my Fiji.app jars folder? 

If i rename either of them .jarNOT so Fiji doesn't load them
the multiple jars warning goes away, but the no such method error stays:
java.lang.NoSuchMethodError: org.itk.simple.Image.getBufferAsByteBuffer()Ljava/nio/ByteBuffer;
see below
(I'm running openCL on my intel xenon E5-2640,  6 core, 12 thread  CPU for now,
as my Geforce GT 730 seems to be flaky for openCL)

cheers

Dan 

OpenCL Convolution time 485
package net.haesleinhuepf.clijx.simpleitk, SimpleITK wrapper for CLIJx-assistant, version 0.0
Overwriting image in cache.
double 1.0
There was a problem with the class org.itk.simple.Image which can be found here:
/C:/Users/ECOOFF~1/DOCUME~1/PORTAB~1/Fiji.app/jars/simpleitk-0.9.0.jar
/C:/Users/ECOOFF~1/DOCUME~1/PORTAB~1/Fiji.app/jars/simpleitk-2.1.0.dev54.jar

WARNING: multiple locations found!
java.lang.NoSuchMethodError: org.itk.simple.Image.getBufferAsByteBuffer()Ljava/nio/ByteBuffer;
	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.clijToITK(CLIJSimpleITKUtilities.java:32)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.simpleITKWienerDeconvolution(SimpleITKWienerDeconvolution.java:51)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.lambda$executeCL$0(SimpleITKWienerDeconvolution.java:45)
	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.runAndCatch(CLIJSimpleITKUtilities.java:131)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.executeCL(SimpleITKWienerDeconvolution.java:45)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.run(AbstractCLIJPlugin.java:478)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:265)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.IJ.runPlugIn(IJ.java:187)
	at net.imagej.legacy.command.LegacyCommand.run(LegacyCommand.java:57)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] java.lang.NoSuchMethodException: Could not find method org.itk.simple.Image.getBufferAsByteBuffer()Ljava/nio/ByteBuffer;
There was a problem with the class org.itk.simple.Image which can be found here:
/C:/Users/ECOOFF~1/DOCUME~1/PORTAB~1/Fiji.app/jars/simpleitk-0.9.0.jar
/C:/Users/ECOOFF~1/DOCUME~1/PORTAB~1/Fiji.app/jars/simpleitk-2.1.0.dev54.jar

WARNING: multiple locations found!
java.lang.NoSuchMethodError: org.itk.simple.Image.getBufferAsByteBuffer()Ljava/nio/ByteBuffer;
	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.clijToITK(CLIJSimpleITKUtilities.java:32)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.simpleITKWienerDeconvolution(SimpleITKWienerDeconvolution.java:51)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.lambda$executeCL$0(SimpleITKWienerDeconvolution.java:45)
	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.runAndCatch(CLIJSimpleITKUtilities.java:131)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.executeCL(SimpleITKWienerDeconvolution.java:45)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.run(AbstractCLIJPlugin.java:478)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:265)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.IJ.runPlugIn(IJ.java:187)
	at net.imagej.legacy.command.LegacyCommand.run(LegacyCommand.java:57)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.clijToITK(CLIJSimpleITKUtilities.java:32)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.simpleITKWienerDeconvolution(SimpleITKWienerDeconvolution.java:51)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.lambda$executeCL$0(SimpleITKWienerDeconvolution.java:45)
	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.runAndCatch(CLIJSimpleITKUtilities.java:131)
	at net.haesleinhuepf.clijx.simpleitk.SimpleITKWienerDeconvolution.executeCL(SimpleITKWienerDeconvolution.java:45)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.run(AbstractCLIJPlugin.java:478)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:265)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.IJ.runPlugIn(IJ.java:187)
	at net.imagej.legacy.command.LegacyCommand.run(LegacyCommand.java:57)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by haesleinhuepf** [comment]
Hey Dan @chalkie666 ,

I'm not sure what comes with the IJ-ITK update site. I would say [ImageJ-ITK](https://github.com/imagej/imagej-itk/) is not maintained. I would suggest deactivating this update site. Btw. if you want to use the extensions, there is a list of update sites you should install: https://clij.github.io/assistant/installation#extensions

Let me know if it works then!

Cheers,
Robert

**Comment by chalkie666** [comment]
Hi @haesleinhuepf 
I turned off the ImageJ-ITK update site, 
and now simpleITK- CLIJ2 stuff is working on my windows pc. 
The Wiener filter i need seems to work, so i will crack on with the rest. 
cheers
D
